sudo: false
language: go
git:
    depth: 1
    submodules: false
install:
    - wget https://github.com/gohugoio/hugo/releases/download/v0.48/hugo_0.48_Linux-64bit.tar.gz
    - tar zxvf hugo_0.48_Linux-64bit.tar.gz
script: ./hugo
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep-history: true
    on:
        branch: master
    local_dir: public
    target_branch: master
